title: Marat Fakhreev

description: >
  Marat Fakhreev's web site. Web, Javascript, Ruby on Rails developer.

social:
  - icon: github
    url:  https://github.com/maratfakhreev

  - icon: vk
    url:  https://vk.com/marat.fakhreev

  - icon: linkedin
    url:  https://www.linkedin.com/in/marat-fakhreev-b7629767

  - icon: inbox
    url:  mailto:marat.fakhreev@gmail.com

markdown: redcarpet
